ALTER TABLE user
ADD COLUMN register_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN phone VARCHAR(20),
ADD COLUMN email VARCHAR(50),
ADD COLUMN status TINYINT NOT NULL DEFAULT 1,
ADD COLUMN last_login_time DATETIME;

UPDATE user SET status = 1 WHERE status IS NULL;