CREATE TABLE product (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  image_url VARCHAR(255),
  activity_id BIGINT,
  original_price DECIMAL(10, 2) NOT NULL,
  seckill_price DECIMAL(10, 2) NOT NULL,
  total_stock INT NOT NULL DEFAULT 0,
  seckill_stock INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1-启用, 0-禁用',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);